//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vs_commitizen.vs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VSPackage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VSPackage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("vs_commitizen.vs.VSPackage", typeof(VSPackage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit.
        /// </summary>
        public static string ButtonCommit {
            get {
                return ResourceManager.GetString("ButtonCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy message.
        /// </summary>
        public static string ButtonCopyMessage {
            get {
                return ResourceManager.GetString("ButtonCopyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed.
        /// </summary>
        public static string ButtonProceed {
            get {
                return ResourceManager.GetString("ButtonProceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ButtonReset {
            get {
                return ResourceManager.GetString("ButtonReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Git_icon {
            get {
                object obj = ResourceManager.GetObject("Git_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide a longer description of the change (optional).
        /// </summary>
        public static string HintBody {
            get {
                return ResourceManager.GetString("HintBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List any breaking changes (optional).
        /// </summary>
        public static string HintBreakingChanges {
            get {
                return ResourceManager.GetString("HintBreakingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List any issues affected by this change (optional). E.g.: &apos;#123&apos;.
        /// </summary>
        public static string HintIssues {
            get {
                return ResourceManager.GetString("HintIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denote the scope of this change (optional).
        /// </summary>
        public static string HintScope {
            get {
                return ResourceManager.GetString("HintScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a short, imperative tense description of the change.
        /// </summary>
        public static string HintSubject {
            get {
                return ResourceManager.GetString("HintSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body :.
        /// </summary>
        public static string LabelBody {
            get {
                return ResourceManager.GetString("LabelBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breaking changes :.
        /// </summary>
        public static string LabelBreakingChanges {
            get {
                return ResourceManager.GetString("LabelBreakingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of changes :.
        /// </summary>
        public static string LabelCommitType {
            get {
                return ResourceManager.GetString("LabelCommitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closes :.
        /// </summary>
        public static string LabelIssues {
            get {
                return ResourceManager.GetString("LabelIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope :.
        /// </summary>
        public static string LabelScope {
            get {
                return ResourceManager.GetString("LabelScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject :.
        /// </summary>
        public static string LabelSubject {
            get {
                return ResourceManager.GetString("LabelSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed to &apos;Changes&apos; view and commit.
        /// </summary>
        public static string TooltipCommit {
            get {
                return ResourceManager.GetString("TooltipCommit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate commit message and copy it to clipboard.
        /// </summary>
        public static string TooltipCopyMessage {
            get {
                return ResourceManager.GetString("TooltipCopyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional ! to draw attention to breaking change. E.g.: &quot;chore!: drop Node 6 from testing matrix&quot;.
        /// </summary>
        public static string TooltipHighlightBreakingChanges {
            get {
                return ResourceManager.GetString("TooltipHighlightBreakingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed to &apos;Changes&apos; view.
        /// </summary>
        public static string TooltipProceed {
            get {
                return ResourceManager.GetString("TooltipProceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all fields.
        /// </summary>
        public static string TooltipReset {
            get {
                return ResourceManager.GetString("TooltipReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Including scope, type and formatting.
        /// </summary>
        public static string TooltipSubjectCounter {
            get {
                return ResourceManager.GetString("TooltipSubjectCounter", resourceCulture);
            }
        }
    }
}
