// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.198
// </auto-generated>
// ------------------------------------------------------------------------------
namespace vs_commitizen
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVsCommitizenPackageString = "c4809955-ac8e-41bf-8d86-faa98b6678ad";
        public const string guidVsCommitizenPackageCmdSetString = "c71925e2-e9ca-4214-9a36-44c8ab847862";
        public const string guidImagesString = "4817493b-b1c9-44a5-af4b-a39633f0f4e1";
        public static Guid guidVsCommitizenPackage = new Guid(guidVsCommitizenPackageString);
        public static Guid guidVsCommitizenPackageCmdSet = new Guid(guidVsCommitizenPackageCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ToolWindow1CommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}
