// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace vs_commitizen
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVsCommitizenPackageString = "c4809955-ac8e-41bf-8d86-faa98b6678ad";
        public static Guid guidVsCommitizenPackage = new Guid(guidVsCommitizenPackageString);

        public const string UIContextGuidString = "d08d84f8-03d8-418e-a03a-1015add01a6f";
        public static Guid UIContextGuid = new Guid(UIContextGuidString);

        public const string guidVsCommitizenPackageCmdSetString = "c71925e2-e9ca-4214-9a36-44c8ab847862";
        public static Guid guidVsCommitizenPackageCmdSet = new Guid(guidVsCommitizenPackageCmdSetString);

        public const string OpenGenerateUserProfileConfigCmdSetString = "a4975378-1743-4009-a4d5-1654a683e957";
        public static Guid OpenGenerateUserProfileConfigCmdSet = new Guid(OpenGenerateUserProfileConfigCmdSetString);

        public const string OpenGenerateLocalConfigCmdSetString = "a4975378-1743-4009-a4d5-1654a683e958";
        public static Guid OpenGenerateLocalConfigCmdSet = new Guid(OpenGenerateLocalConfigCmdSetString);

        public const string guidImagesString = "4817493b-b1c9-44a5-af4b-a39633f0f4e1";
        public static Guid guidImages = new Guid(guidImagesString);

        public const string guidImages2String = "b8ba0b3c-2fca-4a93-9fda-70276a399b8f";
        public static Guid guidImages2 = new Guid(guidImages2String);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int TopLevelMenu = 0x1021;
        public const int MyMenuGroup = 0x1020;
        public const int cmdidVsCommitizenCommand = 0x0100;
        public const int OpenGenerateUserProfileConfigCmd = 0x0100;
        public const int OpenGenerateLocalConfigCmd = 0x0101;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
        public const int bmpOpen = 0x0001;
    }
}