name: Publish to VS Marketplace

env:
  config: Release
  solution: vs-commitizen.sln
  vsixContainer: ${{ github.workspace }}\vs-commitizen.vsix

on:
  push:
    branches-ignore: 
      - master

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.0
      
      - uses: nuget/setup-nuget@v1
        with:
          nuget-version: '5.x'

      - name: Add VSTest to PATH
        uses: darenm/Setup-VSTest@v1

      - name: NuGet restore ${{ env.solution }}
        run: nuget restore ${{ env.solution }}

      - name: MSBuild ${{ env.solution }}
        run: |
          msbuild ${{ env.solution }} /p:Configuration=${{ env.config }} /p:TargetVsixContainer=${{ env.vsixContainer }} /p:DeployExtension=False /verbosity:minimal
        
      - name: show
        run: |
          cat ${{ env.vsixContainer }}
