# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Publish release to marketplace
        id: publish
        uses: mrluje/vs-marketplace-publisher@v2
        with:
          pat: ${{ secrets.vs_pat }}
          manifestPath: vs-commitizen/Resources/vsixManifest.json
          useLatestReleaseAsset: true
